### ISSUE TITLE
Jasonがいない日々に問題を解決する潜在力を発掘した-`д´-

### ISSUE THREAD

**Issue by VickieYan** [Ningersan/vk-hits-me-every-day#3]
T T 没有Jason和Bill的今天，一切只能靠自己了
做点赞的时候发现用componentWillReceiveProps钩子拿到的props比实际的滞后一点
所以有时候能得到正确的效果，刷一刷又不能了。、
终于在被逼无奈下翻了翻文档，发现componentWillReceiveProps还给了一个nextProps的参数。
小红心终于每次都能够点亮了。
万岁~

**Comment by Ningersan** [comment]
vk棒棒哒
撒花～
